### PR TITLE
#161046982 Create login page 

### PR DESCRIPTION
**Pull request by Georgeygigz**
**What does this PR do?**
It creates a login form

**Description of Task to be completed?**
 1. creating a login page with a form 
 2. This form contains email and password fields
 2. Styling the page
 
**What are the stories in the pivotal tracker**
<code>#161046982</code>

**How should this be manually tested?**
Clone the this <code> [repo](https://github.com/Georgeygigz/store-manager)</code> to your local machine:
**screenshot**
screenshot 341

### CODE REVIEW

**Comment by wandesky** [comment]
What do you think about having a navbar and logo at the top?

**Comment by Allan690** [comment]
The color for the login button methinks is too shouting

**Comment by Allan690** [comment]
The design is good, generally

**Comment by Georgeygigz** [comment]
@wadensky Thanks for the comment, what do you mean by nav bar?

**Pull request closed without merging**
